Normalization: y

In [2]:
import numpy as np

#Create a random 5 x 5 ndarray and store it to variable X.
X = np.random.rand(5,5)

mean = X.mean()
std = X.std()

#Normalize X.
normalized = (X - mean) /std

#Save your normalized ndarray as X_normalized.npy.
np.save('X_normalized.npy', normalized)

print("Variables: \n", X)
print("\nNormalized: \n", np.load('X_normalized.npy'))

Variables: 
 [[0.49082345 0.08395412 0.56135803 0.45461297 0.84788237]
 [0.9866897  0.68275554 0.76270311 0.48744823 0.12482808]
 [0.32756722 0.18059391 0.56359363 0.87125776 0.24311224]
 [0.46448382 0.31854575 0.33693482 0.58510527 0.17408994]
 [0.75764803 0.86627231 0.91718655 0.37423808 0.30691665]]

Normalized: 
 [[-0.07627767 -1.62798224  0.19272473 -0.21437597  1.28546165]
 [ 1.81484038  0.65570649  0.96060785 -0.08914997 -1.47209851]
 [-0.6988988  -1.25942068  0.2012508   1.37460993 -1.02099035]
 [-0.17673085 -0.73330458 -0.66317297  0.28329117 -1.2842253 ]
 [ 0.94132895  1.3555966   1.54977162 -0.52090705 -0.77765523]]


Divisible by 3 Problem:

In [64]:
import numpy as np

# squares of the first 100 positive integers.
n = np.arange(1, 101)** 2


#Create the following 10 x 10 ndarray.
a = n.reshape(10, 10)
#All the elements that are divisible by 3.
divisible_by_3 = n[n % 3 == 0]

b = divisible_by_3.reshape(3,-1)

#Save the result as div_by_3.npy.
np.save('div_by_3.npy', b)

print("10x10 array: \n", a) 
print("\nNumbers Divisible by 3: \n", np.load('div_by_3.npy'))

10x10 array: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers Divisible by 3: 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
